// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKr-T1ZivThJQ_j6ejM-LaWzBKkj3BFPs',
    appId: '1:687049583687:web:809fef28eac9def7e3d562',
    messagingSenderId: '687049583687',
    projectId: 'kinksme-a9c9d',
    authDomain: 'kinksme-a9c9d.firebaseapp.com',
    databaseURL: 'https://kinksme-a9c9d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kinksme-a9c9d.firebasestorage.app',
    measurementId: 'G-0TW9PMP3HM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLr5lAjd9zvRiD7aPOpNfIwMdpJ3kseiM',
    appId: '1:687049583687:android:35997035c0b65a58e3d562',
    messagingSenderId: '687049583687',
    projectId: 'kinksme-a9c9d',
    databaseURL: 'https://kinksme-a9c9d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kinksme-a9c9d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZPch0RbNmjkZ4p-DSrcPtcmXTGrXwwJg',
    appId: '1:687049583687:ios:e58ba7c0c7e8ebc6e3d562',
    messagingSenderId: '687049583687',
    projectId: 'kinksme-a9c9d',
    databaseURL: 'https://kinksme-a9c9d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kinksme-a9c9d.firebasestorage.app',
    androidClientId: '687049583687-bbnhber8o5cutc5glteeb4buf6jg9d40.apps.googleusercontent.com',
    iosBundleId: 'com.example.kinksme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZPch0RbNmjkZ4p-DSrcPtcmXTGrXwwJg',
    appId: '1:687049583687:ios:e58ba7c0c7e8ebc6e3d562',
    messagingSenderId: '687049583687',
    projectId: 'kinksme-a9c9d',
    databaseURL: 'https://kinksme-a9c9d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kinksme-a9c9d.firebasestorage.app',
    androidClientId: '687049583687-bbnhber8o5cutc5glteeb4buf6jg9d40.apps.googleusercontent.com',
    iosBundleId: 'com.example.kinksme',
  );

}